# infrastructure/kubernetes/auth-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: adherant-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: adherant/auth-service:latest
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3001"
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: adherant_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password123
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: adherant-platform
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001

---
