# infrastructure/kubernetes/document-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: adherant-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document-service
        image: adherant/document-service:latest
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3003"
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: adherant_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password123
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        ports:
        - containerPort: 3003
        volumeMounts:
        - name: document-storage
          mountPath: /app/uploads
        livenessProbe:
          httpGet:
            path: /api/documents/health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: document-storage
        persistentVolumeClaim:
          claimName: document-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: adherant-platform
spec:
  selector:
    app: document-service
  ports:
  - port: 3003
    targetPort: 3003

---
