# infrastructure/kubernetes/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adherant-ingress
  namespace: adherant-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
spec:
  rules:
  - host: api.adherant.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 3000

---
# PVC for file storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avatar-pvc
  namespace: adherant-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-pvc
  namespace: adherant-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
# JWT Secret
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: adherant-platform
type: Opaque
data:
  secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl # base64 encoded