# infrastructure/kubernetes/profile-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: adherant-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: adherant/profile-service:latest
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3002"
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: adherant_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password123
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        ports:
        - containerPort: 3002
        volumeMounts:
        - name: avatar-storage
          mountPath: /app/uploads
        livenessProbe:
          httpGet:
            path: /api/profile/health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: avatar-storage
        persistentVolumeClaim:
          claimName: avatar-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: adherant-platform
spec:
  selector:
    app: profile-service
  ports:
  - port: 3002
    targetPort: 3002

---
